### ISSUE TITLE
Auto fill the project name/component name

### ISSUE THREAD

**Issue by narutaro** [aws-greengrass/aws-greengrass-gdk-cli#101]
**Feature Description**

Hi, thank for creating really useful tool. `gdk`'s auto-configuration generation saves my time very much. I would like to suggest further auto-configuration for project name/component name

**Use Case**

When initializing a project, generate component name in the `gdk-config.json` - `PythonHelloWorld` in this example. 

```json
{
  "component": {
    "com.example.PythonHelloWorld": {
      "author": "Me",
      "version": "NEXT_PATCH",
      "build": {
        "build_system": "zip"
      },
      "publish": {
        "bucket": "gg-comp",
        "region": "ap-northeast-1"
      }
    }
  },
  "gdk_version": "1.0.0"
}
```

Also, generate the artifact's zip file name as well as the project directory name in the file path - `HelloWorld` in this example.

```yaml
---
RecipeFormatVersion: "2020-01-25"
ComponentName: "{COMPONENT_NAME}"
ComponentVersion: "{COMPONENT_VERSION}"
ComponentDescription: "Sending Modbus readings to SiteWise"
ComponentPublisher: "{COMPONENT_AUTHOR}"
ComponentConfiguration:
  DefaultConfiguration:
    Message: "World"
Manifests:
  - Platform:
      os: all
    Artifacts:
      - URI: "s3://BUCKET_NAME/COMPONENT_NAME/COMPONENT_VERSION/HelloWorld.zip"
        Unarchive: ZIP
    Lifecycle:
      Install: "pip3 install --user -r {artifacts:decompressedPath}/HelloWorld/requirements.txt"
      Run: "python3 -u {artifacts:decompressedPath}/HelloWorld/main.py {configuration:/Message}"
```

so that you don't have to update manually. 

**Proposed Solution**

Add another argument for example `--from` and `--to`

```
gdk component init -l python --from HelloWorld --to CiaoMondo
``` 

then it will generate

```json
{
  "component": {
    "com.example.CiaoMondo": {
      "author": "Me",
      "version": "NEXT_PATCH",
      "build": {
        "build_system": "zip"
      },
      "publish": {
        "bucket": "gg-comp",
        "region": "ap-northeast-1"
      }
    }
  },
  "gdk_version": "1.0.0"
}
```
and 

```yaml
RecipeFormatVersion: "2020-01-25"
ComponentName: "{COMPONENT_NAME}"
ComponentVersion: "{COMPONENT_VERSION}"
ComponentDescription: "Sending Modbus readings to SiteWise"
ComponentPublisher: "{COMPONENT_AUTHOR}"
ComponentConfiguration:
  DefaultConfiguration:
    Message: "World"
Manifests:
  - Platform:
      os: all
    Artifacts:
      - URI: "s3://BUCKET_NAME/COMPONENT_NAME/COMPONENT_VERSION/CiaoMondo.zip"
        Unarchive: ZIP
    Lifecycle:
      Install: "pip3 install --user -r {artifacts:decompressedPath}/CiaoMondo/requirements.txt"
      Run: "python3 -u {artifacts:decompressedPath}/CiaoMondo/main.py {configuration:/Message}"
```

**Other**
Add detailed explanation, stacktraces, related issues, links for us to have context, etc

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change
