### ISSUE TITLE
component build

### ISSUE THREAD

**Issue by wrmay** [aws-greengrass/aws-greengrass-gdk-cli#52]
**Describe the bug**
The s3 artifact URI in built recipe file does not reflect the bucket name, component name and component version configured in the gdk config file.  

**To Reproduce**
In a directory, "hello", run ` gdk component init -l python -t HelloWorld`.
Edit `gdk-config.json` and replace the placeholders as shown below.
```
{
  "component": {
    "com.example.PythonHelloWorld": {
      "author": "Me",
      "version": "NEXT_PATCH",
      "build": {
        "build_system": "zip"
      },
      "publish": {
        "bucket": "gg-component-bucket",
        "region": "us-east-1"
      }
    }
  },
  "gdk_version": "1.0.0"
}
```

Edit `recipe.yaml`, change the name of the zip file to "hello.zip" as shown below

```yaml

---
RecipeFormatVersion: "2020-01-25"
ComponentName: "{COMPONENT_NAME}"
ComponentVersion: "{COMPONENT_VERSION}"
ComponentDescription: "This is simple Hello World component written in Python."
ComponentPublisher: "{COMPONENT_AUTHOR}"
ComponentConfiguration:
  DefaultConfiguration:
    Message: "World"
Manifests:
  - Platform:
      os: all
    Artifacts:
      - URI: "s3://BUCKET_NAME/COMPONENT_NAME/COMPONENT_VERSION/hello.zip"
        Unarchive: ZIP
    Lifecycle:
      Run: "python3 -u {artifacts:decompressedPath}/HelloWorld/main.py {configuration:/Message}"
```

run `gdk component build`

**Expected behavior**
The artifact URI in `greengrass-build/recipes/recipe.yaml` reflects the bucket name, component name and component version configured in `gdk-config.json`.

**Actual behavior**
The artifact URI is "s3://BUCKET_NAME/COMPONENT_NAME/COMPONENT_VERSION/hello.zip"

**Environment**
 - OS:Darwin MacBook-Pro.local 21.2.0 Darwin Kernel Version 21.2.0: Sun Nov 28 20:28:54 PST 2021; root:xnu-8019.61.5~1/RELEASE_X86_64 x86_64
 - JDK version: NA
 - Nucleus version: NA

**Additional context**
